name: rick_and_morty_riverpod
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.0
  json_serializable: ^6.9.3
  riverpod_lint: ^2.6.5
  riverpod_generator: ^2.6.5

flutter:
  assets:
    - .env
  uses-material-design: true
  generate: true
